baseurl = "http://lony.github.io"
languageCode = "en"
title = "[x]"
copyright = "<a href=\"/post/2017/cli-commands/\">&copy;</a> <a href=\"https://getgoetz.com\">Goetz Epperlein</a> 2016 - 2018"
googleAnalytics = "UA-83817537-1"
theme = "bulmera"
paginate = 3
summarylength = 30

[taxonomies]
tag = "tags"

[params.meta]
keywords = [ "tech", "it", "politics", "europe" ]
description = "Private blog about tech, politics and europe"
name = "Goetz Epperlein"
